[Task] Modified theme common for header and footer sa 5384
stakater/stakater-docs-mkdocs-theme pull request #8
Opened 2024-03-14 18:40 UTC by RSAK56

# Description
1. Modified header and footer for MTO docs theme common
2. Adjusted dark and light theme
3. Modified body content
4. Shifted content to theme common

Fixes # (issue)
UI/UX / Theme update

# Type of change
Enhancement

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] UI/UX modification
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-14 22:38 UTC, karl-johan-grahn requested changes

2024-03-14 22:38 UTC, karl-johan-grahn commented on mkdocs.yml
> +      emoji_generator: !!python/name:material.extensions.emoji.to_svg
Should be
```
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```

2024-03-18 08:30 UTC, RSAK56 commented on mkdocs.yml
> +      emoji_generator: !!python/name:material.extensions.emoji.to_svg
Modified pymdownx.emoji as mentioned.

2024-03-21 09:34 UTC, ufateh commented on mkdocs.yml
> +  custom_dir: dist/_theme
what does it do? why do we need it? it can be different for different doc projects?

2024-03-21 09:34 UTC, ufateh commented on mkdocs.yml
> +      title: On this page
what does this do?

2024-03-21 09:34 UTC, ufateh commented on resources/assets/images/logo-dark.png
this one seems to have a different length than logo-light.png
check if this is a mistake.

2024-03-21 09:34 UTC, ufateh commented on resources/assets/images/magnify.png
i thought we went back to default icon in search bar. Check if its a mistake?

2024-03-21 09:34 UTC, ufateh commented on resources/assets/svg/down-arrow.svg
down-arrow.svg
magnify.svg
for twitter logo, replace it with 'X' logo.

2024-03-21 09:34 UTC, ufateh commented on resources/assets/svg/down-arrow.svg
make sure we only have those icons/svgs which we are using.

2024-03-21 09:34 UTC, ufateh commented on resources/main.html
> +{% endblock %}
verify that it is working fine.

2024-03-21 09:39 UTC, ufateh commented on resources/partials/javascripts/nav-links.html
> +        anchor.style.color = "#EA7845";
this hard-coded color, do you think it will be changed in future?

2024-03-21 09:41 UTC, ufateh commented on resources/partials/javascripts/palette.html
do we need this file?

2024-03-21 09:43 UTC, ufateh commented on resources/partials/palette.html
> +  }
it is the same color as we saw earlier. if you think we won't have to change this in future, leave it as it is. Otherwise, we need to pick it from themes

2024-03-21 09:44 UTC, ufateh commented on resources/partials/palette.html
> +  }
also, do we need this file?

2024-03-21 09:45 UTC, ufateh commented on resources/partials/search.html
have we made any modifications in this file? if not, we need to remove this, along with its related javascript.

2024-03-21 09:45 UTC, ufateh commented on resources/partials/search.html
if its only about class, we need to do that in theme css. custom_css file.

2024-03-21 12:03 UTC, RSAK56 commented on mkdocs.yml
> +  custom_dir: dist/_theme
To add custom style sheet to _theme and acts as a build-directory path resolver for dist

2024-03-21 12:03 UTC, RSAK56 commented on mkdocs.yml
> +      title: On this page
This is the title for the table of content to be displayed on the right side. By default it says ToC but if we need to override that with our custom title we can do that as above.

2024-03-21 12:04 UTC, RSAK56 commented on resources/assets/images/logo-dark.png
Will update this as soon as I receive the updated version of logo

2024-03-21 12:05 UTC, RSAK56 commented on resources/assets/images/magnify.png
Yes the icons have been removed already they are not being used with the current search bar

2024-03-21 12:05 UTC, RSAK56 commented on resources/assets/svg/down-arrow.svg
Magnify has been removed and X logo is requested. Apart from that down arrow is being used in the header

2024-03-21 18:55 UTC, RSAK56 commented on resources/partials/javascripts/palette.html
Yes we do need this file. I might need to modify in near future for some changes I have to get approved later on.

2024-03-21 18:59 UTC, RSAK56 commented on resources/partials/javascripts/nav-links.html
> +        anchor.style.color = "#EA7845";
No it won't be changed in the future, also it's a script tag where it's being used. But will try to move it to the CSS section.

2024-03-21 19:01 UTC, RSAK56 commented on resources/partials/palette.html
> +  }
Yes it won't be changed in the future. But we can shift it to CSS later.

Secondly we need this file since the script is required and it is being imported inside the current file and if future modifications get approved I might need to make changes to it.

2024-03-21 19:14 UTC, RSAK56 commented on resources/partials/search.html
Removed and moved styles to the global CSS

2024-03-22 10:38 UTC, RSAK56 commented on mkdocs.yml
> +      emoji_generator: !!python/name:material.extensions.emoji.to_svg
So basically I have went through modifying the emoji_generator and emoji_index as suggested. But the following warning occurs:
```
WARNING -  Material emoji logic has been officially moved into mkdocs-material
           version 9.4. Please use Material's 'material.extensions.emoji.twemoji'
           instead of 'materialx.emoji.twemoji' in your 'mkdocs.yml' file.
```

Stating that the version update requires us to use  **material.extensions.emoji.twemoji** instead. Therefore I have replaced it with the following.

2024-03-27 10:14 UTC, RSAK56 commented on resources/main.html
> +{% endblock %}
We can monitor this after the deployment and re-validate and fix it if any change is required.

2024-03-27 10:14 UTC, ufateh commented
going to merge this now

2024-03-27 10:16 UTC, ufateh approved these changes
approving this, we had the initial demo and it looks fine apart from few improvements like fonts, alignment which is minor atm.

2024-04-01 18:01 UTC, karl-johan-grahn approved these changes

2024-04-01 18:02 UTC, merged